// Code generated by statesman; DO NOT EDIT.

package fix

import (
	_ "embed"

	"github.com/andrioid/statesman"
	"github.com/andrioid/statesman/schema"
)

//go:embed fix.machine.json
var statesmanMachineJSON []byte

var fixDefinition = func() *statesman.Definition {
	d, err := schema.Load(statesmanMachineJSON)
	if err != nil {
		panic("statesman: fix: " + err.Error())
	}
	return d
}()

// States holds the machine's typed state IDs.
var States = struct {
	Editing statesman.StateID
	Testing statesman.StateID
	Done    statesman.StateID
	Failed  statesman.StateID
}{
	Editing: "editing",
	Testing: "testing",
	Done:    "done",
	Failed:  "failed",
}

// EventType implementations for schema-referenced events.

type EditDone struct{ Output EditResult }

func (EditDone) fixEvent()         {}
func (EditDone) EventType() string { return "done.invoke.edit" }

type TestDone struct{ Output TestResult }

func (TestDone) fixEvent()         {}
func (TestDone) EventType() string { return "done.invoke.test" }

type EditError struct{ Err error }

func (EditError) fixEvent()         {}
func (EditError) EventType() string { return "error.invoke.edit" }

type TestError struct{ Err error }

func (TestError) fixEvent()         {}
func (TestError) EventType() string { return "error.invoke.test" }

// ActionResult is the sealed sum returned by action methods.
type ActionResult interface{ isActionResult() }

type Assign struct{ Fields ContextFields }
type Noop struct{}

func (Assign) isActionResult() {}
func (Noop) isActionResult()   {}

// Context embeds the user-authored ContextFields (v1: no typed child refs).
type Context struct{ ContextFields }

// Implementations is the user-implemented behavior interface: one method per
// action, guard, and invoke-input callsite. Methods run synchronously on the
// actor goroutine, so two runtime contracts apply (statesman decisions 39, 41):
//
//   - The ctx parameter is read-only. Context is treated as immutable; mutating
//     ctx in place corrupts the published snapshot and breaks rollback. Return an
//     ActionResult to change context instead.
//   - Methods must not panic. The actor loop has no recover(): a panic crashes
//     the actor goroutine and can stall its parent. Panics are programming errors.
type Implementations interface {
	SavePatchOnEditDone(ctx Context, evt EditDone) ActionResult
	NextAttemptOnTestDone(ctx Context, evt TestDone) ActionResult
	TestsPassedOnTestDone(ctx Context, evt TestDone) bool
	CanRetryOnTestDone(ctx Context, evt TestDone) bool
	ApplyEditInput(ctx Context) EditInput
	RunTestsInput(ctx Context) TestInput
}

// NewFixMachine builds an unstarted machine wired to impl.
func NewFixMachine(impl Implementations, opts ...statesman.Option) *statesman.Machine[Context, Event] {
	m := statesman.NewMachine[Context, Event](fixDefinition, Context{}, makeApplier(impl), makeGuard(impl), opts...)
	m.RegisterInvoke("edit", statesman.PromiseActor[Context, Event, EditInput, EditResult](ApplyEdit, impl.ApplyEditInput,
		func(o EditResult) Event { return EditDone{Output: o} },
		func(e error) Event { return EditError{Err: e} }))
	m.RegisterInvoke("test", statesman.PromiseActor[Context, Event, TestInput, TestResult](RunTests, impl.RunTestsInput,
		func(o TestResult) Event { return TestDone{Output: o} },
		func(e error) Event { return TestError{Err: e} }))
	return m
}

func makeApplier(impl Implementations) func(int, Context, Event) statesman.AppliedEffect[Context] {
	return func(cs int, ctx Context, evt Event) statesman.AppliedEffect[Context] {
		switch cs {
		case 0:
			return applyResult(ctx, impl.SavePatchOnEditDone(ctx, evt.(EditDone)))
		case 1:
			return applyResult(ctx, impl.NextAttemptOnTestDone(ctx, evt.(TestDone)))
		}
		return statesman.AppliedEffect[Context]{Kind: statesman.EffectNoop}
	}
}

func applyResult(ctx Context, r ActionResult) statesman.AppliedEffect[Context] {
	switch v := r.(type) {
	case Assign:
		return statesman.AppliedEffect[Context]{Kind: statesman.EffectAssign, Ctx: Context{ContextFields: v.Fields}}
	}
	return statesman.AppliedEffect[Context]{Kind: statesman.EffectNoop}
}

func makeGuard(impl Implementations) func(int, Context, Event) bool {
	return func(cs int, ctx Context, evt Event) bool {
		switch cs {
		case 0:
			return impl.TestsPassedOnTestDone(ctx, evt.(TestDone))
		case 1:
			return impl.CanRetryOnTestDone(ctx, evt.(TestDone))
		}
		return true
	}
}
