// Code generated by statesman; DO NOT EDIT.

package submach

import (
	_ "embed"

	"github.com/andrioid/statesman"
	"github.com/andrioid/statesman/internal/codegen/testdata/submach/child"
	"github.com/andrioid/statesman/schema"
)

//go:embed parent.machine.json
var statesmanMachineJSON []byte

var parentDefinition = func() *statesman.Definition {
	d, err := schema.Load(statesmanMachineJSON)
	if err != nil {
		panic("statesman: parent: " + err.Error())
	}
	return d
}()

// States holds the machine's typed state IDs.
var States = struct {
	Running statesman.StateID
	Done    statesman.StateID
	Failed  statesman.StateID
}{
	Running: "running",
	Done:    "done",
	Failed:  "failed",
}

// EventType implementations for schema-referenced events.

type RunDone struct{ Output child.Context }

func (RunDone) parentEvent()      {}
func (RunDone) EventType() string { return "done.invoke.run" }

type RunError struct{ Err error }

func (RunError) parentEvent()      {}
func (RunError) EventType() string { return "error.invoke.run" }

// ActionResult is the sealed sum returned by action methods.
type ActionResult interface{ isActionResult() }

type Assign struct{ Fields ContextFields }
type Noop struct{}

func (Assign) isActionResult() {}
func (Noop) isActionResult()   {}

// Context embeds the user-authored ContextFields (v1: no typed child refs).
type Context struct{ ContextFields }

// Implementations is the user-implemented behavior interface: one method per
// action, guard, and invoke-input callsite. Methods run synchronously on the
// actor goroutine, so two runtime contracts apply (statesman decisions 39, 41):
//
//   - The ctx parameter is read-only. Context is treated as immutable; mutating
//     ctx in place corrupts the published snapshot and breaks rollback. Return an
//     ActionResult to change context instead.
//   - Methods must not panic. The actor loop has no recover(): a panic crashes
//     the actor goroutine and can stall its parent. Panics are programming errors.
type Implementations interface {
	RunChildInput(ctx Context) child.Context
}

// NewParentMachine builds an unstarted machine wired to impl.
func NewParentMachine(impl Implementations, opts ...statesman.Option) *statesman.Machine[Context, Event] {
	m := statesman.NewMachine[Context, Event](parentDefinition, Context{}, makeApplier(impl), makeGuard(impl), opts...)
	m.RegisterInvoke("run", statesman.MachineActor[Context, Event, child.Context, child.Event](RunChild, impl.RunChildInput,
		func(s statesman.Snapshot[child.Context]) Event { return RunDone{Output: s.Context} },
		func(s statesman.Snapshot[child.Context]) Event { return RunError{Err: s.ErrorReason} }))
	return m
}

func makeApplier(impl Implementations) func(int, Context, Event) statesman.AppliedEffect[Context] {
	return func(cs int, ctx Context, evt Event) statesman.AppliedEffect[Context] {
		switch cs {
		}
		return statesman.AppliedEffect[Context]{Kind: statesman.EffectNoop}
	}
}

func applyResult(ctx Context, r ActionResult) statesman.AppliedEffect[Context] {
	switch v := r.(type) {
	case Assign:
		return statesman.AppliedEffect[Context]{Kind: statesman.EffectAssign, Ctx: Context{ContextFields: v.Fields}}
	}
	return statesman.AppliedEffect[Context]{Kind: statesman.EffectNoop}
}

func makeGuard(impl Implementations) func(int, Context, Event) bool {
	return func(cs int, ctx Context, evt Event) bool {
		switch cs {
		}
		return true
	}
}
