// Code generated by statesman; DO NOT EDIT.

package investigate

import (
	_ "embed"
	"time"

	"github.com/andrioid/statesman"
	"github.com/andrioid/statesman/schema"
)

//go:embed investigate.machine.json
var statesmanMachineJSON []byte

var investigateDefinition = func() *statesman.Definition {
	d, err := schema.Load(statesmanMachineJSON)
	if err != nil {
		panic("statesman: investigate: " + err.Error())
	}
	return d
}()

// States holds the machine's typed state IDs.
var States = struct {
	Analysing statesman.StateID
	Done      statesman.StateID
	Failed    statesman.StateID
}{
	Analysing: "analysing",
	Done:      "done",
	Failed:    "failed",
}

// EventType implementations for schema-referenced events.

type AnalyseDone struct{ Output AnalyseResult }

func (AnalyseDone) investigateEvent() {}
func (AnalyseDone) EventType() string { return "done.invoke.analyse" }

type AnalyseError struct{ Err error }

func (AnalyseError) investigateEvent() {}
func (AnalyseError) EventType() string { return "error.invoke.analyse" }

// ActionResult is the sealed sum returned by action methods.
type ActionResult interface{ isActionResult() }

type Assign struct{ Fields ContextFields }
type Noop struct{}

func (Assign) isActionResult() {}
func (Noop) isActionResult()   {}

// Context embeds the user-authored ContextFields (v1: no typed child refs).
type Context struct{ ContextFields }

// Implementations is the user-implemented behavior interface: one method per
// action, guard, and invoke-input callsite. Methods run synchronously on the
// actor goroutine, so two runtime contracts apply (statesman decisions 39, 41):
//
//   - The ctx parameter is read-only. Context is treated as immutable; mutating
//     ctx in place corrupts the published snapshot and breaks rollback. Return an
//     ActionResult to change context instead.
//   - Methods must not panic. The actor loop has no recover(): a panic crashes
//     the actor goroutine and can stall its parent. Panics are programming errors.
type Implementations interface {
	SaveFindingsOnAnalyseDone(ctx Context, evt AnalyseDone) ActionResult
	AnalyseCodeInput(ctx Context) AnalyseInput
}

// NewInvestigateMachine builds an unstarted machine wired to impl.
func NewInvestigateMachine(impl Implementations, opts ...statesman.Option) *statesman.Machine[Context, Event] {
	opts = append(opts, statesman.WithDelays(map[string]time.Duration{
		"AnalyseTimeout": AnalyseTimeout,
	}))
	m := statesman.NewMachine[Context, Event](investigateDefinition, Context{}, makeApplier(impl), makeGuard(impl), opts...)
	m.RegisterInvoke("analyse", statesman.PromiseActor[Context, Event, AnalyseInput, AnalyseResult](AnalyseCode, impl.AnalyseCodeInput,
		func(o AnalyseResult) Event { return AnalyseDone{Output: o} },
		func(e error) Event { return AnalyseError{Err: e} }))
	return m
}

func makeApplier(impl Implementations) func(int, Context, Event) statesman.AppliedEffect[Context] {
	return func(cs int, ctx Context, evt Event) statesman.AppliedEffect[Context] {
		switch cs {
		case 0:
			return applyResult(ctx, impl.SaveFindingsOnAnalyseDone(ctx, evt.(AnalyseDone)))
		}
		return statesman.AppliedEffect[Context]{Kind: statesman.EffectNoop}
	}
}

func applyResult(ctx Context, r ActionResult) statesman.AppliedEffect[Context] {
	switch v := r.(type) {
	case Assign:
		return statesman.AppliedEffect[Context]{Kind: statesman.EffectAssign, Ctx: Context{ContextFields: v.Fields}}
	}
	return statesman.AppliedEffect[Context]{Kind: statesman.EffectNoop}
}

func makeGuard(impl Implementations) func(int, Context, Event) bool {
	return func(cs int, ctx Context, evt Event) bool {
		switch cs {
		}
		return true
	}
}
