// Code generated by statesman; DO NOT EDIT.

package orderpkg

import (
	"context"
	_ "embed"
	"time"

	"github.com/andrioid/statesman"
	"github.com/andrioid/statesman/schema"
)

//go:embed order.machine.json
var statesmanMachineJSON []byte

var orderDefinition = func() *statesman.Definition {
	d, err := schema.Load(statesmanMachineJSON)
	if err != nil {
		panic("statesman: order: " + err.Error())
	}
	return d
}()

// States holds the machine's typed state IDs.
var States = struct {
	Idle               statesman.StateID
	Processing         statesman.StateID
	ProcessingCharging statesman.StateID
	Retrying           statesman.StateID
	Confirming         statesman.StateID
	Done               statesman.StateID
	Errored            statesman.StateID
}{
	Idle:               "idle",
	Processing:         "processing",
	ProcessingCharging: "processing.charging",
	Retrying:           "retrying",
	Confirming:         "confirming",
	Done:               "done",
	Errored:            "errored",
}

// EventType implementations for schema-referenced events.
func (Confirm) EventType() string { return "CONFIRM" }
func (Submit) EventType() string  { return "SUBMIT" }

type ChargeDone struct{ Output ChargeResult }

func (ChargeDone) orderEvent()       {}
func (ChargeDone) EventType() string { return "done.invoke.charge" }

type ChargeError struct{ Err error }

func (ChargeError) orderEvent()       {}
func (ChargeError) EventType() string { return "error.invoke.charge" }

// ActionResult is the sealed sum returned by action methods.
type ActionResult interface{ isActionResult() }

type Assign struct{ Fields ContextFields }
type Noop struct{}

func (Assign) isActionResult() {}
func (Noop) isActionResult()   {}

type SendToInventory struct{ Command InventoryCommand }

func (SendToInventory) isActionResult() {}

// Context embeds the user-authored ContextFields (v1: no typed child refs).
type Context struct{ ContextFields }

// Implementations is the user-implemented behavior interface: one method per
// action, guard, and invoke-input callsite. Methods run synchronously on the
// actor goroutine, so two runtime contracts apply (statesman decisions 39, 41):
//
//   - The ctx parameter is read-only. Context is treated as immutable; mutating
//     ctx in place corrupts the published snapshot and breaks rollback. Return an
//     ActionResult to change context instead.
//   - Methods must not panic. The actor loop has no recover(): a panic crashes
//     the actor goroutine and can stall its parent. Panics are programming errors.
type Implementations interface {
	ValidateFormOnSubmit(ctx Context, evt Submit) ActionResult
	IncrementRetriesOnProcessingCharging(ctx Context) ActionResult
	IncrementRetriesOnChargeError(ctx Context, evt ChargeError) ActionResult
	HasRetriesLeftOnProcessingCharging(ctx Context) bool
	HasRetriesLeftOnChargeError(ctx Context, evt ChargeError) bool
	ChargeCardInput(ctx Context) ChargeInput
}

// NewOrderMachine builds an unstarted machine wired to impl.
func NewOrderMachine(impl Implementations, opts ...statesman.Option) *statesman.Machine[Context, Event] {
	opts = append(opts, statesman.WithDelays(map[string]time.Duration{
		"RetryDelay": RetryDelay,
	}))
	m := statesman.NewMachine[Context, Event](orderDefinition, Context{}, makeApplier(impl), makeGuard(impl), opts...)
	m.RegisterInvoke("inventory", statesman.CallbackActor[Context, Event, InventoryCommand](
		func(ctx context.Context, emit func(Event), recv <-chan InventoryCommand) error {
			return WatchInventory(ctx, func(e InventoryEvent) { emit(e) }, recv)
		}, nil, nil))
	m.RegisterInvoke("charge", statesman.PromiseActor[Context, Event, ChargeInput, ChargeResult](ChargeCard, impl.ChargeCardInput,
		func(o ChargeResult) Event { return ChargeDone{Output: o} },
		func(e error) Event { return ChargeError{Err: e} }))
	return m
}

func makeApplier(impl Implementations) func(int, Context, Event) statesman.AppliedEffect[Context] {
	return func(cs int, ctx Context, evt Event) statesman.AppliedEffect[Context] {
		switch cs {
		case 0:
			return applyResult(ctx, impl.ValidateFormOnSubmit(ctx, evt.(Submit)))
		case 1:
			return applyResult(ctx, impl.IncrementRetriesOnProcessingCharging(ctx))
		case 2:
			return applyResult(ctx, impl.IncrementRetriesOnChargeError(ctx, evt.(ChargeError)))
		}
		return statesman.AppliedEffect[Context]{Kind: statesman.EffectNoop}
	}
}

func applyResult(ctx Context, r ActionResult) statesman.AppliedEffect[Context] {
	switch v := r.(type) {
	case Assign:
		return statesman.AppliedEffect[Context]{Kind: statesman.EffectAssign, Ctx: Context{ContextFields: v.Fields}}
	case SendToInventory:
		return statesman.AppliedEffect[Context]{Kind: statesman.EffectSend, Target: statesman.ActorAddress("inventory"), Event: v.Command}
	}
	return statesman.AppliedEffect[Context]{Kind: statesman.EffectNoop}
}

func makeGuard(impl Implementations) func(int, Context, Event) bool {
	return func(cs int, ctx Context, evt Event) bool {
		switch cs {
		case 0:
			return impl.HasRetriesLeftOnProcessingCharging(ctx)
		case 1:
			return impl.HasRetriesLeftOnChargeError(ctx, evt.(ChargeError))
		}
		return true
	}
}
