package codegen

import (
	"fmt"
	"go/format"
	"go/types"
	"sort"
	"strings"

	"github.com/andrioid/statesman"
)

// Emit produces the generated facade (<id>.machine.gen.go) for a resolved machine. v1 conventions
// (documented deviations from the architecture where the schema under-specifies):
// flat States; Context embeds only ContextFields (typed child refs deferred);
// per-callsite method names <Action>On<Event|State>; invoke input via an Impl
// mapper method; SendTo routes by invoke id.
func Emit(res *Resolution, def *statesman.Definition) ([]byte, error) {
	pkgName := res.Pkg.Name
	g := &gen{def: def, res: res, localPkg: res.Pkg.Types}
	g.buildCallsites()

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by statesman; DO NOT EDIT.\n\npackage %s\n\n", pkgName)
	b.WriteString("import (\n\t_ \"embed\"\n")
	if g.usesContext() {
		b.WriteString("\t\"context\"\n")
	}
	if g.usesTime() {
		b.WriteString("\t\"time\"\n")
	}
	b.WriteString("\n\t\"github.com/andrioid/statesman\"\n\t\"github.com/andrioid/statesman/schema\"\n)\n\n")

	g.emitDefinition(&b)
	g.emitStates(&b)
	g.emitEvents(&b)
	g.emitActionResult(&b)
	g.emitContext(&b)
	g.emitImplementations(&b)
	g.emitConstructor(&b)

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("gofmt generated source: %w\n%s", err, b.String())
	}
	return src, nil
}

type gen struct {
	def      *statesman.Definition
	res      *Resolution
	localPkg *types.Package
	actions  []callsite // action callsites, by id
	guards   []callsite // guard callsites, by id
}

type callsite struct {
	id      int
	typ     string // action/guard type
	event   string // triggering descriptor ("" => context shape)
	evented bool   // true => narrow the event
	source  statesman.StateID
}

// machineName is the exported prefix: the machine id, PascalCased.
func (g *gen) machineName() string { return NormalizeName(g.def.ID) }

func (g *gen) buildCallsites() {
	amax, gmax := g.def.ActionCount, g.def.GuardCount
	g.actions = make([]callsite, amax)
	g.guards = make([]callsite, gmax)
	var visit func(n *statesman.StateNode)
	record := func(t *statesman.Transition) {
		evented := t.Event != "" && !t.IsAfter && !isGenerated(t.Event)
		// onDone/onError are generated but DO carry a typed event; treat as evented.
		if strings.HasPrefix(t.Event, "done.invoke.") || strings.HasPrefix(t.Event, "error.invoke.") {
			evented = true
		}
		if t.Guard != nil {
			g.guards[t.Guard.Callsite] = callsite{id: t.Guard.Callsite, typ: t.Guard.Type, event: t.Event, evented: evented, source: t.Source.ID}
		}
		for _, a := range t.Actions {
			g.actions[a.Callsite] = callsite{id: a.Callsite, typ: a.Type, event: t.Event, evented: evented, source: t.Source.ID}
		}
	}
	visit = func(n *statesman.StateNode) {
		for _, a := range n.Entry {
			g.actions[a.Callsite] = callsite{id: a.Callsite, typ: a.Type, source: n.ID}
		}
		for _, t := range n.Transitions {
			record(t)
		}
		for _, a := range n.Exit {
			g.actions[a.Callsite] = callsite{id: a.Callsite, typ: a.Type, source: n.ID}
		}
		for _, iv := range n.Invokes {
			for _, t := range iv.OnDone {
				record(t)
			}
			for _, t := range iv.OnError {
				record(t)
			}
		}
		for _, c := range n.Children {
			visit(c)
		}
	}
	visit(g.def.Root)
}

// methodName derives the per-callsite method name. Evented -> <Action>On<Event>;
// otherwise -> <Action>On<FlatStateID>.
func methodName(c callsite) string {
	if c.evented {
		ev, _ := EventGoName(c.event)
		return NormalizeName(c.typ) + "On" + ev
	}
	return NormalizeName(c.typ) + "On" + flatID(c.source)
}

func flatID(id statesman.StateID) string { return NormalizeName(string(id)) }

func (g *gen) emitDefinition(b *strings.Builder) {
	fmt.Fprintf(b, "//go:embed %s.machine.json\nvar statesmanMachineJSON []byte\n\n", g.def.ID)
	fmt.Fprintf(b, "var %sDefinition = func() *statesman.Definition {\n", lower(g.machineName()))
	fmt.Fprintf(b, "\td, err := schema.Load(statesmanMachineJSON)\n\tif err != nil {\n\t\tpanic(\"statesman: %s: \" + err.Error())\n\t}\n\treturn d\n}()\n\n", g.def.ID)
}

func (g *gen) emitStates(b *strings.Builder) {
	var nodes []*statesman.StateNode
	var collect func(n *statesman.StateNode)
	collect = func(n *statesman.StateNode) {
		if n.ID != "" {
			nodes = append(nodes, n)
		}
		for _, c := range n.Children {
			collect(c)
		}
	}
	collect(g.def.Root)
	sort.Slice(nodes, func(i, j int) bool { return nodes[i].DocOrder < nodes[j].DocOrder })

	b.WriteString("// States holds the machine's typed state IDs.\nvar States = struct {\n")
	for _, n := range nodes {
		fmt.Fprintf(b, "\t%s statesman.StateID\n", flatID(n.ID))
	}
	b.WriteString("}{\n")
	for _, n := range nodes {
		fmt.Fprintf(b, "\t%s: %q,\n", flatID(n.ID), string(n.ID))
	}
	b.WriteString("}\n\n")
}

func (g *gen) emitEvents(b *strings.Builder) {
	// EventType for schema-referenced user events.
	descs := make([]string, 0, len(g.res.Events))
	for d := range g.res.Events {
		descs = append(descs, d)
	}
	sort.Strings(descs)
	b.WriteString("// EventType implementations for schema-referenced events.\n")
	for _, d := range descs {
		fmt.Fprintf(b, "func (%s) EventType() string { return %q }\n", g.res.Events[d].GoName, d)
	}
	b.WriteString("\n")

	// Generated done.invoke / error.invoke event types.
	marker := g.eventMarker()
	for _, di := range g.doneErrorEvents() {
		if di.done {
			fmt.Fprintf(b, "type %s struct{ Output %s }\n", di.goName, di.output)
		} else {
			fmt.Fprintf(b, "type %s struct{ Err error }\n", di.goName)
		}
		if marker != "" {
			fmt.Fprintf(b, "func (%s) %s() {}\n", di.goName, marker)
		}
		fmt.Fprintf(b, "func (%s) EventType() string { return %q }\n\n", di.goName, di.descriptor)
	}
}

type doneErrEvent struct {
	descriptor string
	goName     string
	done       bool
	output     string // for done events
}

func (g *gen) doneErrorEvents() []doneErrEvent {
	seen := map[string]bool{}
	var out []doneErrEvent
	idToOut := g.invokeOutputs()
	var visit func(n *statesman.StateNode)
	add := func(event string) {
		if seen[event] || !(strings.HasPrefix(event, "done.invoke.") || strings.HasPrefix(event, "error.invoke.")) {
			return
		}
		seen[event] = true
		name, _ := EventGoName(event)
		isDone := strings.HasPrefix(event, "done.invoke.")
		de := doneErrEvent{descriptor: event, goName: name, done: isDone}
		if isDone {
			id := strings.TrimPrefix(event, "done.invoke.")
			de.output = idToOut[id]
			if de.output == "" {
				de.output = "struct{}"
			}
		}
		out = append(out, de)
	}
	visit = func(n *statesman.StateNode) {
		for _, t := range n.Transitions {
			add(t.Event)
		}
		for _, iv := range n.Invokes {
			for _, t := range iv.OnDone {
				add(t.Event)
			}
			for _, t := range iv.OnError {
				add(t.Event)
			}
		}
		for _, c := range n.Children {
			visit(c)
		}
	}
	visit(g.def.Root)
	sort.Slice(out, func(i, j int) bool { return out[i].descriptor < out[j].descriptor })
	return out
}

// invokeOutputs maps invoke id -> promise output type string (for done events).
func (g *gen) invokeOutputs() map[string]string {
	m := map[string]string{}
	var visit func(n *statesman.StateNode)
	visit = func(n *statesman.StateNode) {
		for _, iv := range n.Invokes {
			if a := g.res.Actors[iv.Src]; a != nil && a.Out != nil {
				m[iv.ID] = g.typeString(a.Out)
			}
		}
		for _, c := range n.Children {
			visit(c)
		}
	}
	visit(g.def.Root)
	return m
}

// eventMarker returns the sealed Event interface's unexported marker method name.
func (g *gen) eventMarker() string {
	obj := g.localPkg.Scope().Lookup("Event")
	tn, ok := obj.(*types.TypeName)
	if !ok {
		return ""
	}
	iface, ok := tn.Type().Underlying().(*types.Interface)
	if !ok {
		return ""
	}
	for i := 0; i < iface.NumMethods(); i++ {
		m := iface.Method(i)
		if !m.Exported() && m.Name() != "EventType" {
			return m.Name()
		}
	}
	return ""
}

func (g *gen) emitActionResult(b *strings.Builder) {
	b.WriteString("// ActionResult is the sealed sum returned by action methods.\n")
	b.WriteString("type ActionResult interface{ isActionResult() }\n\n")
	b.WriteString("type Assign struct{ Fields ContextFields }\n")
	b.WriteString("type Noop struct{}\n")
	b.WriteString("func (Assign) isActionResult() {}\n")
	b.WriteString("func (Noop) isActionResult() {}\n")
	for _, s := range g.sendableInvokes() {
		fmt.Fprintf(b, "type SendTo%s struct{ Command %s }\n", s.goName, s.cmdType)
		fmt.Fprintf(b, "func (SendTo%s) isActionResult() {}\n", s.goName)
	}
	b.WriteString("\n")
}

type sendable struct {
	id      string
	goName  string // NormalizeName(id)
	cmdType string
}

// sendableInvokes are callback/machine invokes (SendTo targets).
func (g *gen) sendableInvokes() []sendable {
	var out []sendable
	var visit func(n *statesman.StateNode)
	visit = func(n *statesman.StateNode) {
		for _, iv := range n.Invokes {
			a := g.res.Actors[iv.Src]
			if a == nil || a.Kind != AdapterCallback {
				continue
			}
			out = append(out, sendable{id: iv.ID, goName: NormalizeName(iv.ID), cmdType: g.callbackCmdType(a)})
		}
		for _, c := range n.Children {
			visit(c)
		}
	}
	visit(g.def.Root)
	sort.Slice(out, func(i, j int) bool { return out[i].id < out[j].id })
	return out
}

// callbackCmdType returns the receive-subset command type of a callback actor.
func (g *gen) callbackCmdType(a *ActorSym) string {
	sig := a.Func.Type().(*types.Signature)
	if sig.Params().Len() != 3 {
		return "statesman.EventBase"
	}
	ch, ok := sig.Params().At(2).Type().Underlying().(*types.Chan)
	if !ok {
		return "statesman.EventBase"
	}
	return g.typeString(ch.Elem())
}

func (g *gen) emitContext(b *strings.Builder) {
	b.WriteString("// Context embeds the user-authored ContextFields (v1: no typed child refs).\n")
	b.WriteString("type Context struct{ ContextFields }\n\n")
}

type implMethod struct {
	name string
	sig  string
}

// implMethods returns the ordered, de-duplicated method set the user must
// implement: one per action, guard, and invoke-input callsite. Shared by the
// generated Implementations interface and `statesman stub`'s Impl skeleton.
func (g *gen) implMethods() []implMethod {
	seen := map[string]bool{}
	var out []implMethod
	add := func(name, sig string) {
		if seen[name] {
			return
		}
		seen[name] = true
		out = append(out, implMethod{name: name, sig: sig})
	}
	for _, c := range g.actions {
		name := methodName(c)
		if c.evented {
			ev, _ := EventGoName(c.event)
			add(name, fmt.Sprintf("%s(ctx Context, evt %s) ActionResult", name, ev))
			continue
		}
		add(name, fmt.Sprintf("%s(ctx Context) ActionResult", name))
	}
	gcounts := g.guardTypeCounts()
	for _, c := range g.guards {
		gt := NormalizeName(c.typ)
		if gcounts[gt] > 1 {
			// Reused guard type: one context-only fallback; per-callsite methods
			// become optional overrides (decision 15).
			add(gt, fmt.Sprintf("%s(ctx Context) bool", gt))
			continue
		}
		name := methodName(c)
		if c.evented {
			ev, _ := EventGoName(c.event)
			add(name, fmt.Sprintf("%s(ctx Context, evt %s) bool", name, ev))
			continue
		}
		add(name, fmt.Sprintf("%s(ctx Context) bool", name))
	}
	for _, im := range g.inputMappers() {
		add(im.method, fmt.Sprintf("%s(ctx Context) %s", im.method, im.inType))
	}
	return out
}

func (g *gen) emitImplementations(b *strings.Builder) {
	b.WriteString(`// Implementations is the user-implemented behavior interface: one method per
// action, guard, and invoke-input callsite. Methods run synchronously on the
// actor goroutine, so two runtime contracts apply (statesman decisions 39, 41):
//
//   - The ctx parameter is read-only. Context is treated as immutable; mutating
//     ctx in place corrupts the published snapshot and breaks rollback. Return an
//     ActionResult to change context instead.
//   - Methods must not panic. The actor loop has no recover(): a panic crashes
//     the actor goroutine and can stall its parent. Panics are programming errors.
`)
	b.WriteString("type Implementations interface {\n")
	for _, m := range g.implMethods() {
		fmt.Fprintf(b, "\t%s\n", m.sig)
	}
	b.WriteString("}\n\n")
}

type inputMapper struct {
	invokeID string
	src      string
	method   string // <Src>Input
	inType   string
}

func (g *gen) inputMappers() []inputMapper {
	var out []inputMapper
	var visit func(n *statesman.StateNode)
	visit = func(n *statesman.StateNode) {
		for _, iv := range n.Invokes {
			a := g.res.Actors[iv.Src]
			if a == nil || a.Kind != AdapterPromise || a.In == nil {
				continue
			}
			out = append(out, inputMapper{invokeID: iv.ID, src: iv.Src, method: NormalizeName(iv.Src) + "Input", inType: g.typeString(a.In)})
		}
		for _, c := range n.Children {
			visit(c)
		}
	}
	visit(g.def.Root)
	sort.Slice(out, func(i, j int) bool { return out[i].invokeID < out[j].invokeID })
	return out
}

func (g *gen) emitConstructor(b *strings.Builder) {
	mn := g.machineName()
	fmt.Fprintf(b, "// New%sMachine builds an unstarted machine wired to impl.\n", mn)
	fmt.Fprintf(b, "func New%sMachine(impl Implementations, opts ...statesman.Option) *statesman.Machine[Context, Event] {\n", mn)
	if delays := g.symbolicDelays(); len(delays) > 0 {
		b.WriteString("\topts = append(opts, statesman.WithDelays(map[string]time.Duration{\n")
		for _, d := range delays {
			fmt.Fprintf(b, "\t\t%q: %s,\n", d, NormalizeName(d))
		}
		b.WriteString("\t}))\n")
	}
	fmt.Fprintf(b, "\tm := statesman.NewMachine[Context, Event](%sDefinition, Context{}, makeApplier(impl), makeGuard(impl), opts...)\n", lower(mn))
	g.emitRegisterInvokes(b)
	b.WriteString("\treturn m\n}\n\n")

	g.emitApplier(b)
	g.emitGuardEval(b)
}

func (g *gen) emitRegisterInvokes(b *strings.Builder) {
	var visit func(n *statesman.StateNode)
	visit = func(n *statesman.StateNode) {
		for _, iv := range n.Invokes {
			a := g.res.Actors[iv.Src]
			if a == nil {
				continue
			}
			switch a.Kind {
			case AdapterPromise:
				doneName, _ := EventGoName("done.invoke." + iv.ID)
				errName, _ := EventGoName("error.invoke." + iv.ID)
				out := g.typeString(a.Out)
				fmt.Fprintf(b, "\tm.RegisterInvoke(%q, statesman.PromiseActor[Context, Event, %s, %s](%s, impl.%sInput,\n",
					iv.ID, g.typeString(a.In), out, a.GoName, NormalizeName(iv.Src))
				fmt.Fprintf(b, "\t\tfunc(o %s) Event { return %s{Output: o} },\n", out, doneName)
				fmt.Fprintf(b, "\t\tfunc(e error) Event { return %s{Err: e} }))\n", errName)
			case AdapterCallback:
				cmd := g.callbackCmdType(a)
				emitType := g.callbackEmitType(a)
				fmt.Fprintf(b, "\tm.RegisterInvoke(%q, statesman.CallbackActor[Context, Event, %s](\n", iv.ID, cmd)
				fmt.Fprintf(b, "\t\tfunc(ctx context.Context, emit func(Event), recv <-chan %s) error {\n", cmd)
				fmt.Fprintf(b, "\t\t\treturn %s(ctx, func(e %s) { emit(e) }, recv)\n\t\t}, nil, nil))\n", a.GoName, emitType)
			}
		}
		for _, c := range n.Children {
			visit(c)
		}
	}
	visit(g.def.Root)
}

func (g *gen) callbackEmitType(a *ActorSym) string {
	sig := a.Func.Type().(*types.Signature)
	if sig.Params().Len() != 3 {
		return "Event"
	}
	fn, ok := sig.Params().At(1).Type().Underlying().(*types.Signature)
	if !ok || fn.Params().Len() != 1 {
		return "Event"
	}
	return g.typeString(fn.Params().At(0).Type())
}

func (g *gen) emitApplier(b *strings.Builder) {
	b.WriteString("func makeApplier(impl Implementations) func(int, Context, Event) statesman.AppliedEffect[Context] {\n")
	b.WriteString("\treturn func(cs int, ctx Context, evt Event) statesman.AppliedEffect[Context] {\n\t\tswitch cs {\n")
	for _, c := range g.actions {
		name := methodName(c)
		if c.evented {
			ev, _ := EventGoName(c.event)
			fmt.Fprintf(b, "\t\tcase %d:\n\t\t\treturn applyResult(ctx, impl.%s(ctx, evt.(%s)))\n", c.id, name, ev)
		} else {
			fmt.Fprintf(b, "\t\tcase %d:\n\t\t\treturn applyResult(ctx, impl.%s(ctx))\n", c.id, name)
		}
	}
	b.WriteString("\t\t}\n\t\treturn statesman.AppliedEffect[Context]{Kind: statesman.EffectNoop}\n\t}\n}\n\n")

	b.WriteString("func applyResult(ctx Context, r ActionResult) statesman.AppliedEffect[Context] {\n\tswitch v := r.(type) {\n")
	b.WriteString("\tcase Assign:\n\t\treturn statesman.AppliedEffect[Context]{Kind: statesman.EffectAssign, Ctx: Context{ContextFields: v.Fields}}\n")
	for _, s := range g.sendableInvokes() {
		fmt.Fprintf(b, "\tcase SendTo%s:\n\t\treturn statesman.AppliedEffect[Context]{Kind: statesman.EffectSend, Target: statesman.ActorAddress(%q), Event: v.Command}\n", s.goName, s.id)
	}
	b.WriteString("\t}\n\treturn statesman.AppliedEffect[Context]{Kind: statesman.EffectNoop}\n}\n\n")
}

// guardTypeCounts counts how many callsites each (normalized) guard type is wired
// on. A type on 2+ callsites gets one context-only fallback method in
// Implementations; its per-callsite methods become optional overrides the guard
// dispatch prefers when present (decision 15).
func (g *gen) guardTypeCounts() map[string]int {
	counts := map[string]int{}
	for _, c := range g.guards {
		counts[NormalizeName(c.typ)]++
	}
	return counts
}

func (g *gen) emitGuardEval(b *strings.Builder) {
	b.WriteString("func makeGuard(impl Implementations) func(int, Context, Event) bool {\n")
	b.WriteString("\treturn func(cs int, ctx Context, evt Event) bool {\n\t\tswitch cs {\n")
	gcounts := g.guardTypeCounts()
	for _, c := range g.guards {
		gt := NormalizeName(c.typ)
		if gcounts[gt] > 1 {
			over := methodName(c)
			if c.evented {
				ev, _ := EventGoName(c.event)
				fmt.Fprintf(b, "\t\tcase %d:\n\t\t\tif o, ok := impl.(interface{ %s(Context, %s) bool }); ok {\n\t\t\t\treturn o.%s(ctx, evt.(%s))\n\t\t\t}\n\t\t\treturn impl.%s(ctx)\n", c.id, over, ev, over, ev, gt)
			} else {
				fmt.Fprintf(b, "\t\tcase %d:\n\t\t\tif o, ok := impl.(interface{ %s(Context) bool }); ok {\n\t\t\t\treturn o.%s(ctx)\n\t\t\t}\n\t\t\treturn impl.%s(ctx)\n", c.id, over, over, gt)
			}
			continue
		}
		name := methodName(c)
		if c.evented {
			ev, _ := EventGoName(c.event)
			fmt.Fprintf(b, "\t\tcase %d:\n\t\t\treturn impl.%s(ctx, evt.(%s))\n", c.id, name, ev)
		} else {
			fmt.Fprintf(b, "\t\tcase %d:\n\t\t\treturn impl.%s(ctx)\n", c.id, name)
		}
	}
	b.WriteString("\t\t}\n\t\treturn true\n\t}\n}\n")
}

func (g *gen) typeString(t types.Type) string {
	if t == nil {
		return "struct{}"
	}
	return types.TypeString(t, func(p *types.Package) string {
		if p == g.localPkg {
			return ""
		}
		return p.Name()
	})
}

func lower(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

// usesContext reports whether the generated code needs the context import
// (callback invokes wrap the user fn with a context.Context parameter).
func (g *gen) usesContext() bool {
	for _, s := range g.sendableInvokes() {
		_ = s
		return true
	}
	return false
}

// usesTime reports whether the generated code needs the time import (symbolic
// after delays are wired via WithDelays(map[string]time.Duration{...})).
func (g *gen) usesTime() bool { return len(g.res.Delays) > 0 }

// symbolicDelays returns the symbolic after-delay names, sorted.
func (g *gen) symbolicDelays() []string {
	out := make([]string, 0, len(g.res.Delays))
	for d := range g.res.Delays {
		out = append(out, d)
	}
	sort.Strings(out)
	return out
}
