// Code generated by statesman; DO NOT EDIT.

package issues

import (
	_ "embed"
	"time"

	"github.com/andrioid/statesman"
	"github.com/andrioid/statesman/examples/issues/fix"
	"github.com/andrioid/statesman/examples/issues/investigate"
	"github.com/andrioid/statesman/schema"
)

//go:embed issues.machine.json
var statesmanMachineJSON []byte

var issuesDefinition = func() *statesman.Definition {
	d, err := schema.Load(statesmanMachineJSON)
	if err != nil {
		panic("statesman: issues: " + err.Error())
	}
	return d
}()

// States holds the machine's typed state IDs.
var States = struct {
	Collecting           statesman.StateID
	CollectingFetching   statesman.StateID
	CollectingBackingOff statesman.StateID
	Classifying          statesman.StateID
	Investigating        statesman.StateID
	Fixing               statesman.StateID
	Summarising          statesman.StateID
	Syncing              statesman.StateID
	SyncingPosting       statesman.StateID
	SyncingBackingOff    statesman.StateID
	Failed               statesman.StateID
	Finished             statesman.StateID
}{
	Collecting:           "collecting",
	CollectingFetching:   "collecting.fetching",
	CollectingBackingOff: "collecting.backingOff",
	Classifying:          "classifying",
	Investigating:        "investigating",
	Fixing:               "fixing",
	Summarising:          "summarising",
	Syncing:              "syncing",
	SyncingPosting:       "syncing.posting",
	SyncingBackingOff:    "syncing.backingOff",
	Failed:               "failed",
	Finished:             "finished",
}

// EventType implementations for schema-referenced events.

type ClassifyDone struct{ Output ClassifyResult }

func (ClassifyDone) issuesEvent()      {}
func (ClassifyDone) EventType() string { return "done.invoke.classify" }

type CollectDone struct{ Output CollectResult }

func (CollectDone) issuesEvent()      {}
func (CollectDone) EventType() string { return "done.invoke.collect" }

type FixDone struct{ Output fix.Context }

func (FixDone) issuesEvent()      {}
func (FixDone) EventType() string { return "done.invoke.fix" }

type InvestigateDone struct{ Output investigate.Context }

func (InvestigateDone) issuesEvent()      {}
func (InvestigateDone) EventType() string { return "done.invoke.investigate" }

type SummariseDone struct{ Output SummariseResult }

func (SummariseDone) issuesEvent()      {}
func (SummariseDone) EventType() string { return "done.invoke.summarise" }

type SyncDone struct{ Output SyncResult }

func (SyncDone) issuesEvent()      {}
func (SyncDone) EventType() string { return "done.invoke.sync" }

type ClassifyError struct{ Err error }

func (ClassifyError) issuesEvent()      {}
func (ClassifyError) EventType() string { return "error.invoke.classify" }

type CollectError struct{ Err error }

func (CollectError) issuesEvent()      {}
func (CollectError) EventType() string { return "error.invoke.collect" }

type FixError struct{ Err error }

func (FixError) issuesEvent()      {}
func (FixError) EventType() string { return "error.invoke.fix" }

type InvestigateError struct{ Err error }

func (InvestigateError) issuesEvent()      {}
func (InvestigateError) EventType() string { return "error.invoke.investigate" }

type SummariseError struct{ Err error }

func (SummariseError) issuesEvent()      {}
func (SummariseError) EventType() string { return "error.invoke.summarise" }

type SyncError struct{ Err error }

func (SyncError) issuesEvent()      {}
func (SyncError) EventType() string { return "error.invoke.sync" }

// ActionResult is the sealed sum returned by action methods.
type ActionResult interface{ isActionResult() }

type Assign struct{ Fields ContextFields }
type Noop struct{}

func (Assign) isActionResult() {}
func (Noop) isActionResult()   {}

// Context embeds the user-authored ContextFields (v1: no typed child refs).
type Context struct{ ContextFields }

// Implementations is the user-implemented behavior interface: one method per
// action, guard, and invoke-input callsite. Methods run synchronously on the
// actor goroutine, so two runtime contracts apply (statesman decisions 39, 41):
//
//   - The ctx parameter is read-only. Context is treated as immutable; mutating
//     ctx in place corrupts the published snapshot and breaks rollback. Return an
//     ActionResult to change context instead.
//   - Methods must not panic. The actor loop has no recover(): a panic crashes
//     the actor goroutine and can stall its parent. Panics are programming errors.
type Implementations interface {
	SavePackageOnCollectDone(ctx Context, evt CollectDone) ActionResult
	RecordFailureOnCollectError(ctx Context, evt CollectError) ActionResult
	NextAttemptOnCollectingBackingOff(ctx Context) ActionResult
	SaveClassificationOnClassifyDone(ctx Context, evt ClassifyDone) ActionResult
	SaveFindingsOnInvestigateDone(ctx Context, evt InvestigateDone) ActionResult
	SavePatchOnFixDone(ctx Context, evt FixDone) ActionResult
	SaveSummaryOnSummariseDone(ctx Context, evt SummariseDone) ActionResult
	RecordFailureOnSyncError(ctx Context, evt SyncError) ActionResult
	NextAttemptOnSyncingBackingOff(ctx Context) ActionResult
	HasAttemptsLeft(ctx Context) bool
	ShouldRetry(ctx Context) bool
	IsActionableOnClassifyDone(ctx Context, evt ClassifyDone) bool
	ClassifyIssueInput(ctx Context) ClassifyInput
	CollectIssueInput(ctx Context) CollectInput
	FixInput(ctx Context) fix.Context
	InvestigateInput(ctx Context) investigate.Context
	SummariseIssueInput(ctx Context) SummariseInput
	SyncIssueInput(ctx Context) SyncInput
}

// NewIssuesMachine builds an unstarted machine wired to impl.
func NewIssuesMachine(impl Implementations, opts ...statesman.Option) *statesman.Machine[Context, Event] {
	opts = append(opts, statesman.WithDelays(map[string]time.Duration{
		"ClassifyTimeout":       ClassifyTimeout,
		"CollectAttemptTimeout": CollectAttemptTimeout,
		"CollectBackoff":        CollectBackoff,
		"CollectDeadline":       CollectDeadline,
		"SummariseTimeout":      SummariseTimeout,
		"SyncAttemptTimeout":    SyncAttemptTimeout,
		"SyncBackoff":           SyncBackoff,
		"SyncDeadline":          SyncDeadline,
	}))
	m := statesman.NewMachine[Context, Event](issuesDefinition, Context{}, makeApplier(impl), makeGuard(impl), opts...)
	m.RegisterInvoke("collect", statesman.PromiseActor[Context, Event, CollectInput, CollectResult](CollectIssue, impl.CollectIssueInput,
		func(o CollectResult) Event { return CollectDone{Output: o} },
		func(e error) Event { return CollectError{Err: e} }))
	m.RegisterInvoke("classify", statesman.PromiseActor[Context, Event, ClassifyInput, ClassifyResult](ClassifyIssue, impl.ClassifyIssueInput,
		func(o ClassifyResult) Event { return ClassifyDone{Output: o} },
		func(e error) Event { return ClassifyError{Err: e} }))
	m.RegisterInvoke("investigate", statesman.MachineActor[Context, Event, investigate.Context, investigate.Event](Investigate, impl.InvestigateInput,
		func(s statesman.Snapshot[investigate.Context]) Event { return InvestigateDone{Output: s.Context} },
		func(s statesman.Snapshot[investigate.Context]) Event { return InvestigateError{Err: s.ErrorReason} }))
	m.RegisterInvoke("fix", statesman.MachineActor[Context, Event, fix.Context, fix.Event](Fix, impl.FixInput,
		func(s statesman.Snapshot[fix.Context]) Event { return FixDone{Output: s.Context} },
		func(s statesman.Snapshot[fix.Context]) Event { return FixError{Err: s.ErrorReason} }))
	m.RegisterInvoke("summarise", statesman.PromiseActor[Context, Event, SummariseInput, SummariseResult](SummariseIssue, impl.SummariseIssueInput,
		func(o SummariseResult) Event { return SummariseDone{Output: o} },
		func(e error) Event { return SummariseError{Err: e} }))
	m.RegisterInvoke("sync", statesman.PromiseActor[Context, Event, SyncInput, SyncResult](SyncIssue, impl.SyncIssueInput,
		func(o SyncResult) Event { return SyncDone{Output: o} },
		func(e error) Event { return SyncError{Err: e} }))
	return m
}

func makeApplier(impl Implementations) func(int, Context, Event) statesman.AppliedEffect[Context] {
	return func(cs int, ctx Context, evt Event) statesman.AppliedEffect[Context] {
		switch cs {
		case 0:
			return applyResult(ctx, impl.SavePackageOnCollectDone(ctx, evt.(CollectDone)))
		case 1:
			return applyResult(ctx, impl.RecordFailureOnCollectError(ctx, evt.(CollectError)))
		case 2:
			return applyResult(ctx, impl.RecordFailureOnCollectError(ctx, evt.(CollectError)))
		case 3:
			return applyResult(ctx, impl.NextAttemptOnCollectingBackingOff(ctx))
		case 4:
			return applyResult(ctx, impl.SaveClassificationOnClassifyDone(ctx, evt.(ClassifyDone)))
		case 5:
			return applyResult(ctx, impl.SaveClassificationOnClassifyDone(ctx, evt.(ClassifyDone)))
		case 6:
			return applyResult(ctx, impl.SaveFindingsOnInvestigateDone(ctx, evt.(InvestigateDone)))
		case 7:
			return applyResult(ctx, impl.SavePatchOnFixDone(ctx, evt.(FixDone)))
		case 8:
			return applyResult(ctx, impl.SaveSummaryOnSummariseDone(ctx, evt.(SummariseDone)))
		case 9:
			return applyResult(ctx, impl.RecordFailureOnSyncError(ctx, evt.(SyncError)))
		case 10:
			return applyResult(ctx, impl.RecordFailureOnSyncError(ctx, evt.(SyncError)))
		case 11:
			return applyResult(ctx, impl.NextAttemptOnSyncingBackingOff(ctx))
		}
		return statesman.AppliedEffect[Context]{Kind: statesman.EffectNoop}
	}
}

func applyResult(ctx Context, r ActionResult) statesman.AppliedEffect[Context] {
	switch v := r.(type) {
	case Assign:
		return statesman.AppliedEffect[Context]{Kind: statesman.EffectAssign, Ctx: Context{ContextFields: v.Fields}}
	}
	return statesman.AppliedEffect[Context]{Kind: statesman.EffectNoop}
}

func makeGuard(impl Implementations) func(int, Context, Event) bool {
	return func(cs int, ctx Context, evt Event) bool {
		switch cs {
		case 0:
			if o, ok := impl.(interface{ HasAttemptsLeftOnCollectingFetching(Context) bool }); ok {
				return o.HasAttemptsLeftOnCollectingFetching(ctx)
			}
			return impl.HasAttemptsLeft(ctx)
		case 1:
			if o, ok := impl.(interface {
				ShouldRetryOnCollectError(Context, CollectError) bool
			}); ok {
				return o.ShouldRetryOnCollectError(ctx, evt.(CollectError))
			}
			return impl.ShouldRetry(ctx)
		case 2:
			return impl.IsActionableOnClassifyDone(ctx, evt.(ClassifyDone))
		case 3:
			if o, ok := impl.(interface{ HasAttemptsLeftOnSyncingPosting(Context) bool }); ok {
				return o.HasAttemptsLeftOnSyncingPosting(ctx)
			}
			return impl.HasAttemptsLeft(ctx)
		case 4:
			if o, ok := impl.(interface{ ShouldRetryOnSyncError(Context, SyncError) bool }); ok {
				return o.ShouldRetryOnSyncError(ctx, evt.(SyncError))
			}
			return impl.ShouldRetry(ctx)
		}
		return true
	}
}
