// Package github is a type-safe GitHub GraphQL client for the issues example,
// generated by genqlient from the vendored public schema. It replaces the gh
// CLI for data operations; gh survives only as a token fallback (see client.go).
package github

//go:generate go tool genqlient genqlient.yaml
