// Code generated by statesman; DO NOT EDIT.

package simple

import (
	_ "embed"

	"github.com/andrioid/statesman"
	"github.com/andrioid/statesman/schema"
)

//go:embed machine.json
var statesmanMachineJSON []byte

var simpleDefinition = func() *statesman.Definition {
	d, err := schema.Load(statesmanMachineJSON)
	if err != nil {
		panic("statesman: simple: " + err.Error())
	}
	return d
}()

// States holds the machine's typed state IDs.
var States = struct {
	Giving statesman.StateID
	Taking statesman.StateID
}{
	Giving: "giving",
	Taking: "taking",
}

// EventType implementations for schema-referenced events.
func (Spin) EventType() string { return "SPIN" }

// ActionResult is the sealed sum returned by action methods.
type ActionResult interface{ isActionResult() }

type Assign struct{ Fields ContextFields }
type Noop struct{}

func (Assign) isActionResult() {}
func (Noop) isActionResult()   {}

// Context embeds the user-authored ContextFields (v1: no typed child refs).
type Context struct{ ContextFields }

// Implementations is the user-implemented behavior interface: one method per
// action, guard, and invoke-input callsite. Methods run synchronously on the
// actor goroutine, so two runtime contracts apply (statesman decisions 39, 41):
//
//   - The ctx parameter is read-only. Context is treated as immutable; mutating
//     ctx in place corrupts the published snapshot and breaks rollback. Return an
//     ActionResult to change context instead.
//   - Methods must not panic. The actor loop has no recover(): a panic crashes
//     the actor goroutine and can stall its parent. Panics are programming errors.
type Implementations interface {
	SpinGivingOnSpin(ctx Context, evt Spin) ActionResult
	SpinTakingOnSpin(ctx Context, evt Spin) ActionResult
	PayingTooMuchOnGiving(ctx Context) bool
	PayingTooLittleOnTaking(ctx Context) bool
}

// NewSimpleMachine builds an unstarted machine wired to impl.
func NewSimpleMachine(impl Implementations, opts ...statesman.Option) *statesman.Machine[Context, Event] {
	m := statesman.NewMachine[Context, Event](simpleDefinition, Context{}, makeApplier(impl), makeGuard(impl), opts...)
	return m
}

func makeApplier(impl Implementations) func(int, Context, Event) statesman.AppliedEffect[Context] {
	return func(cs int, ctx Context, evt Event) statesman.AppliedEffect[Context] {
		switch cs {
		case 0:
			return applyResult(ctx, impl.SpinGivingOnSpin(ctx, evt.(Spin)))
		case 1:
			return applyResult(ctx, impl.SpinTakingOnSpin(ctx, evt.(Spin)))
		}
		return statesman.AppliedEffect[Context]{Kind: statesman.EffectNoop}
	}
}

func applyResult(ctx Context, r ActionResult) statesman.AppliedEffect[Context] {
	switch v := r.(type) {
	case Assign:
		return statesman.AppliedEffect[Context]{Kind: statesman.EffectAssign, Ctx: Context{ContextFields: v.Fields}}
	}
	return statesman.AppliedEffect[Context]{Kind: statesman.EffectNoop}
}

func makeGuard(impl Implementations) func(int, Context, Event) bool {
	return func(cs int, ctx Context, evt Event) bool {
		switch cs {
		case 0:
			return impl.PayingTooMuchOnGiving(ctx)
		case 1:
			return impl.PayingTooLittleOnTaking(ctx)
		}
		return true
	}
}
